# syntax=docker/dockerfile:1
FROM osrf/ros:noetic-desktop-full

# Install Packages for Installing Python Packages
RUN /bin/bash -c "apt-get update -y &&\
    apt-get install -y python3-pip &&\
    apt-get install -y python3-all-dev &&\
    apt-get install -y python3-rospkg &&\
    apt-get install -y ros-noetic-geodesy ros-noetic-pcl-ros ros-noetic-nmea-msgs ros-noetic-libg2o &&\
    apt-get install -y ros-noetic-desktop-full --fix-missing"

RUN /bin/bash -c "apt-get update -y &&\
    apt-get install -y build-essential &&\
    apt-get install -y libssl-dev &&\
    apt-get install -y libffi-dev &&\
    apt-get install -y libxml2-dev &&\
    apt-get install -y libxslt1-dev &&\
    apt-get install -y git &&\
    apt-get install -y zlib1g-dev"

# Create catkin workspace
# Install UR Robot Driver
RUN /bin/bash -c "apt-get update &&\
    source /opt/ros/noetic/setup.bash &&\
    mkdir -p ~/catkin_ws/src &&\
    cd ~/catkin_ws/src &&\
    git clone https://github.com/koide3/ndt_omp.git &&\
    git clone https://github.com/SMRT-AIST/fast_gicp.git --recursive &&\
    git clone https://github.com/koide3/hdl_graph_slam &&\
    cd .. && catkin_make -DCMAKE_BUILD_TYPE=Release &&\
    source devel/setup.bash"

# Install Pynput Package for Keyboard Input Control
RUN /bin/bash -c "python3 -m pip install pynput &&\
    python3 -m pip install scipy &&\
    apt-get update -y &&\
    apt-get install -y python3-tk &&\
    apt-get install -y tk-dev"